### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by jforberg** [fsek/sysop#3]
We need to structure our backups.

Everyone who runs some kind of backup service, or knows about one, please post here.

@henrikssn @davidwessman @lham etc. etc.

**Comment by jforberg** [comment]
I'll start: I don't run any backups, or know definitely that any backup is run and works.

The only job I run is the system upgrade /root/bin/aptgrade.

**Comment by davidwessman** [comment]
Backups of something specific? Or everything?

**Comment by henrikssn** [comment]
There are backups running internally on the server, but no externally that I know of.

We previously ran backups towards esek but they apparently revoked our account some years ago. Its a pity since we had a really nice solution going on there. It was even properly encrypted.

**Comment by jforberg** [comment]
Ok. @henrikssn is that a full root backup? The most sensitive parts of our data are probably the documents share and the databases. If we can backup those then we are mostly covered.

I'm sorry that the esek solution did not work out. I was actually the one who came up with that solution some years ago. 

It's not really acceptable IMO to not make offsite backups, especially for an organisation like Fsek that has a >2 million SEK turnover (IIRC). At the **very** least, we could buy a cheap USB disk and hook it up to one of TLTH's servers.

Maybe I'll start looking into this seeing as we are handling software on a much more professional level now.

**Comment by davidwessman** [comment]
> Maybe I'll start looking into this seeing as we are handling software on a much more professional level now.

:+1:

**Comment by jforberg** [comment]
Daily, delta-coded mysqlbackups are implemented. More backups should follow.
